### ISSUE TITLE
So how exactly do I install this?

### ISSUE THREAD

**Issue by TheCottonEyeJoe** [Juanan7676/netcoin#2]
The installation instructions just says to use wget or pastebin, but gives no pastebin id. I tried wget with the master file link, but that only installed a program that doesn't run.

Am I missing something, or?

**Comment by Juanan7676** [comment]
You have to copy all the files manually using pastebin (or Ctrl-C, Ctrl-V). Or compress the whole thing into a zip file if you have a library for de-compressing files in your in-game computer.

**Comment by TheCottonEyeJoe** [comment]
I'll see if I can find a library for that, otherwise does anything need to be in specific directories besides the ones in miner and node?

**Comment by Juanan7676** [comment]
In theory it doesn't matter, as long as you copy it in the same structure that it is in the repo.

**Comment by Juanan7676** [comment]
Also see #1 to configure the program!

**Comment by Juanan7676** [comment]
There is now an install script to easily download everything.

**Comment by TheCottonEyeJoe** [comment]
Alright, awesome.
